name: CI Pipeline - Docker Hub Deployment

on:
  push:
    branches:
    - main
    - develop
    - peter_branch
  pull_request:
    branches:
    - main
    - develop
    - peter_branch

jobs:
  docker-build-push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    env:

      DOCKER_USERNAME: peterukpabi4
      DOCKER_PASSWORD: Newday12345@

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/smartsphere:${{ github.sha }} .

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/smartsphere:${{ github.sha }}

